#include <tests/container/btree_speedtest_main_template.hpp>
void run_all_args() {
    testOptions.insert(MAPLIZE);

// generated by gen-all-options.py
#include <tests/container/btree_speedtest_maplize_options.hpp>

}
