#include <tests/container/btree_speedtest_main_template.hpp>
void run_all_args() {
    testOptions.insert(REBALANCE);

// generated by gen-all-options.py
#include <tests/container/btree_speedtest_rebalance_options.hpp>

}
