#include <tests/container/btree_speedtest_main_template.hpp>
void run_all_args() {
    testOptions.insert(UPDATE);

// generated by gen-all-options.py
#include <tests/container/btree_speedtest_update_options.hpp>

}
