#include <tests/container/btree_speedtest_main_template.hpp>
void run_all_args() {
    testOptions.insert(LOOKUP);

// generated by gen-all-options.py
#include <tests/container/btree_speedtest_lookup_options.hpp>

}
