#include <tests/container/btree_speedtest_main_template.hpp>
void run_all_args() {
    testOptions.insert(BTREEMIX);

// generated by gen-all-options.py
#include <tests/container/btree_speedtest_btreemix_options.hpp>

}
